# Generated by Django 4.2.28 on 2026-02-23 14:49

from django.db import migrations, models
import hiring.models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_add_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=hiring.models.profile_picture_upload_path),
        ),
    ]
