# Generated by Django 4.2.28 on 2026-04-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='AI evaluation feedback for coding answers'),
        ),
        migrations.AddField(
            model_name='answer',
            name='code_response',
            field=models.TextField(blank=True, help_text='Submitted code for coding questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='coding_instructions',
            field=models.TextField(blank=True, help_text='Detailed problem statement for coding questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='expected_output',
            field=models.TextField(blank=True, help_text='Reference expected output or solution description'),
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('sql', 'SQL')], default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Pre-filled code template for the candidate'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('CD', 'Coding')], default='MC', max_length=2),
        ),
        migrations.CreateModel(
            name='CodingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Input for this test case')),
                ('expected_output', models.TextField(help_text='Expected output for this test case')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden test cases are not shown to candidates')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='hiring.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
